[project]
name = "weather_predictor_app"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "numpy",
    "xgboost",
    "catboost",
    "pandas",
    "jupyterlab",
    "scikit-learn<1.6",
    "matplotlib",
    "shap",

]
