services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/streamlit_frontend
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/main
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge

