_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 23
                - 24
                - 55
            "4": 3.11.5
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
colsample_bytree:
    value: 0.8
eta:
    value: 0.1
eval_metric:
    value: logloss
max_depth:
    value: 4
objective:
    value: reg:squarederror
subsample:
    value: 0.8
